baseURL = "https://fmko.kapicka.cz"
languageCode = "en-US"
title = "Fmko"
enableGitInfo = false
disableKinds = ["taxonomyTerm"]
disableHugoGeneratorInject = true
enableEmoji = true

[menu]
  [[menu.main]]
    identifier = "2013"
    name = "2013"
    url = "/2013/"
  [[menu.main]]
    identifier = "2014"
    name = "2014"
    url = "/2014/"
  [[menu.main]]
    identifier = "2018"
    name = "2018"
    url = "/2018/"
  [[menu.main]]
    identifier = "2022"
    name = "2022"
    url = "/2022/"
